"use client";

import { useEffect, useMemo, useState } from "react";
import { allQuestions, modules } from "@/data/modules";
import { instructorQuestions } from "@/data/courseContent/instructor";
import { Question } from "@/data/types";

type View = "home" | "mission" | "lab" | "case" | "explore" | "review" | "progress";
type Player = { xp: number; streak: number; answered: string[]; correct: string[]; weak: Record<string, number>; badges: string[] };
const initial: Player = { xp: 240, streak: 3, answered: [], correct: [], weak: {}, badges: ["Anatomical Position Pro"] };
const level = (xp: number) => Math.min(6, Math.floor(xp / 250) + 1);
const levels = ["Anatomy Rookie", "Body Explorer", "Anatomy Detective", "Clinical Thinker", "A&P Scholar", "Future Nurse"];
const storage = "ap-quest-player-v1";

export default function Page() {
  const [view, setView] = useState<View>("home"); const [player, setPlayer] = useState<Player>(initial);
  const [selectedModule, setSelectedModule] = useState("foundations"); const [questionIndex, setQuestionIndex] = useState(0);
  const [choice, setChoice] = useState<number | null>(null); const [checked, setChecked] = useState(false);
  useEffect(() => { const saved = localStorage.getItem(storage); if (saved) setPlayer(JSON.parse(saved)); }, []);
  useEffect(() => { localStorage.setItem(storage, JSON.stringify(player)); }, [player]);
  const selected = useMemo(() => modules.find((m) => m.id === selectedModule) ?? modules[0], [selectedModule]);
  const missionQuestions = selected.questions;
  const current = missionQuestions[questionIndex % missionQuestions.length];
  const mastery = Math.min(100, Math.round((player.correct.length / Math.max(1, player.answered.length)) * 100));
  const answer = (q: Question, answerIndex: number) => {
    if (checked) return; setChoice(answerIndex); setChecked(true); const good = answerIndex === q.answer;
    setPlayer((p) => ({ ...p, xp: p.xp + (good ? q.xp : 5), streak: good ? p.streak + 1 : 0, answered: [...new Set([...p.answered, q.id])], correct: good ? [...new Set([...p.correct, q.id])] : p.correct, weak: good ? p.weak : { ...p.weak, [q.topic]: (p.weak[q.topic] ?? 0) + 1 }, badges: good && p.correct.length + 1 >= 10 && !p.badges.includes("Quest Starter") ? [...p.badges, "Quest Starter"] : p.badges }));
  };
  const next = () => { setChoice(null); setChecked(false); setQuestionIndex((n) => n + 1); };
  const startModule = (id: string) => { setSelectedModule(id); setQuestionIndex(0); setChoice(null); setChecked(false); setView("mission"); };
  return <main><aside className="sidebar"><div className="brand"><span className="logo">✦</span><span>A&P <b>Quest</b></span></div><nav>{([ ["home","⌂","Home"], ["mission","◈","Missions"], ["lab","⌁","Practice Lab"], ["case","✚","Clinical Detective"], ["explore","◎","Anatomy Explorer"], ["review","↻","Review weak areas"], ["progress","▥","My progress"] ] as [View,string,string][]).map(([id,icon,label]) => <button key={id} className={view === id ? "nav active" : "nav"} onClick={() => setView(id)}><span>{icon}</span>{label}</button>)}</nav><div className="side-tip"><span>⚕</span><p><b>Daily challenge</b><br />Find the appendix<br /><em>+150 XP</em></p></div></aside><section className="mobile-nav"><span className="brand"><span className="logo">✦</span>A&P Quest</span><button onClick={() => setView("home")}>⌂</button><button onClick={() => setView("mission")}>◈</button><button onClick={() => setView("progress")}>▥</button></section><div className="content"><header><div><p className="eyebrow">BIOS 251 STUDY ADVENTURE</p><h1>{view === "home" ? "Good to see you, Jordan." : titleFor(view)}</h1></div><div className="player-chip"><span className="avatar">J</span><div><b>Level {level(player.xp)}</b><small>{levels[level(player.xp)-1]}</small></div><strong>⚡ {player.xp}</strong></div></header>{view === "home" && <Home player={player} mastery={mastery} onStart={() => startModule("foundations")} onView={setView} onModule={startModule} />} {view === "mission" && <Mission module={selected} question={current} index={questionIndex} choice={choice} checked={checked} onAnswer={answer} onNext={next} onBack={() => setView("home")} />} {view === "lab" && <Lab onDone={() => setView("home")} />} {view === "case" && <Case player={player} />} {view === "explore" && <Explorer />} {view === "review" && <Review player={player} onQuestion={(q) => { setSelectedModule(modules.find((m) => m.title === q.module)?.id ?? "foundations"); setView("mission"); }} />} {view === "progress" && <Progress player={player} mastery={mastery} />}</div></main>;
}
function titleFor(v: View) { const titles: Record<View, string> = { home: "", mission: "Choose your mission", lab: "Practice Lab", case: "Clinical Detective", explore: "Anatomy Explorer", review: "Let’s strengthen this", progress: "Your learning journey" }; return titles[v]; }
function Home({ player, mastery, onStart, onView, onModule }: { player: Player; mastery: number; onStart: () => void; onView: (v: View) => void; onModule: (id: string) => void }) { return <><div className="hero"><div><span className="pill">CURRENT MISSION</span><h2>Locate the problem</h2><p>Build your anatomy foundation, then apply it in quick clinical scenarios.</p><button className="primary" onClick={onStart}>Continue mission <span>→</span></button></div><div className="hero-art"><div className="orbit one">+</div><div className="body-icon">♁</div><div className="orbit two">✦</div><small>FOUNDATIONS<br /><b>1 / 7</b></small></div></div><div className="stats"><Stat label="TOTAL XP" value={player.xp.toString()} icon="⚡" /><Stat label="CURRENT STREAK" value={`${player.streak} days`} icon="◒" /><Stat label="MASTERY" value={`${mastery}%`} icon="◉" /></div><div className="grid-section"><div className="section-title"><div><p className="eyebrow">YOUR QUEST MAP</p><h2>Keep exploring</h2></div><button className="text-button" onClick={() => onView("mission")}>See all missions →</button></div><div className="module-grid">{modules.slice(0,4).map((m, i) => <button className={`module-card ${m.color}`} onClick={() => onModule(m.id)} key={m.id}><span className="module-number">0{i+1}</span><span className="module-icon">{m.icon}</span><b>{m.title}</b><small>{m.questions.length} challenges</small><div className="mini-progress"><i style={{width: i === 0 ? "42%" : "0%"}} /></div></button>)}</div></div><div className="lower-grid"><button className="feature-card lab-card" onClick={() => onView("lab")}><span>◈</span><div><p className="eyebrow">PRACTICE LAB</p><h3>Identify. Match. Master.</h3><p>Quick hands-on style challenges for your lab practical.</p></div><b>Try lab rush →</b></button><button className="feature-card review-card" onClick={() => onView("review")}><span>↻</span><div><p className="eyebrow">ADAPTIVE REVIEW</p><h3>Review your weak areas</h3><p>Small wins, targeted to what needs practice.</p></div><b>Build confidence →</b></button></div></> }
function Stat({label,value,icon}:{label:string;value:string;icon:string}) { return <div className="stat"><span>{icon}</span><div><small>{label}</small><b>{value}</b></div></div> }
function Mission({ module, question, index, choice, checked, onAnswer, onNext, onBack }: { module: typeof modules[number]; question: Question; index: number; choice: number | null; checked: boolean; onAnswer:(q:Question,n:number)=>void; onNext:()=>void; onBack:()=>void }) { const correct = choice === question.answer; return <div className="mission-wrap"><button className="back" onClick={onBack}>← Back to map</button><div className="mission-head"><div><span className="pill">MISSION {String(index+1).padStart(2,"0")}</span><h2>{module.title}: {module.subtitle}</h2></div><span className="question-count">{(index % module.questions.length) + 1} / {module.questions.length}</span></div><div className="progress-line"><i style={{width:`${((index % module.questions.length + 1)/module.questions.length)*100}%`}} /></div><article className="question-card"><div className="question-top"><span className="topic-tag">{question.topic}</span><span>⚡ +{question.xp} XP</span></div><h2>{question.question}</h2><div className="choices">{question.options.map((option,n) => <button key={option} disabled={checked} onClick={() => onAnswer(question,n)} className={`choice ${choice === n ? (n === question.answer ? "correct" : "wrong") : checked && n === question.answer ? "correct" : ""}`}><span>{"ABCD"[n]}</span>{option}{checked && n === question.answer && <i>✓</i>}</button>)}</div>{checked && <div className={correct ? "feedback good" : "feedback gentle"}><b>{correct ? "Great job! +"+question.xp+" XP" : "Almost there — let’s figure out why."}</b><p>{question.explanation}</p><button className="primary" onClick={onNext}>{correct ? "Next challenge" : "Keep going"} →</button></div>}</article></div> }
function Lab({onDone}:{onDone:()=>void}) { const [pick,setPick]=useState<string|null>(null); const right="Thoracic cavity"; return <div className="lab-wrap"><div className="lab-banner"><span>⌁</span><div><p className="eyebrow">LAB RUSH</p><h2>Spot the structure</h2><p>Educational practice only. Add course images later in <code>data/courseContent/instructor</code>.</p></div><strong>01 / 05</strong></div><div className="lab-body"><div className="torso"><span className="head"/><span className="chest">♥<i>THORACIC</i></span><span className="abdomen">●<i>ABDOMINAL</i></span><span className="pelvis">◒<i>PELVIC</i></span></div><div><span className="pill">IDENTIFY THE SPACE</span><h2>Which cavity houses the heart?</h2>{["Cranial cavity","Thoracic cavity","Abdominal cavity","Pelvic cavity"].map(o=><button onClick={()=>setPick(o)} className={`lab-option ${pick===o?(o===right?"correct":"wrong"):""}`} key={o}>{o}</button>)}{pick && <div className="feedback good"><b>{pick===right?"Correct — excellent lab work!":"Not quite. The heart sits in the thoracic cavity."}</b><p>The thoracic cavity is above the diaphragm and includes the heart and lungs.</p><button className="primary" onClick={onDone}>Finish lab rush →</button></div>}</div></div></div> }
function Case({player}:{player:Player}) { const [step,setStep]=useState(0); const qs=[{q:"Where is the pain now localized?",o:["Right lower quadrant","Left upper quadrant","Right upper quadrant"],a:0,e:"The scenario localizes pain to the right lower quadrant (RLQ)."},{q:"Which regional term best fits this location?",o:["Right iliac (inguinal) region","Epigastric region","Left hypochondriac region"],a:0,e:"The right iliac/inguinal region lies in the lower right of the nine-region scheme."}]; const current=qs[step]; const [answer,setAnswer]=useState<number|null>(null); return <div className="case-wrap"><div className="case-intro"><span>✚</span><div><p className="eyebrow">EDUCATIONAL CASE STUDY</p><h2>Find the Pain</h2><p>A patient’s pain begins near the umbilicus and later localizes to the lower right abdomen. Use anatomy language to investigate.</p></div><small>This activity teaches anatomy. It does not provide medical advice or diagnosis.</small></div>{step < qs.length ? <article className="question-card case-question"><span className="pill">CLUE {step+1} OF {qs.length}</span><h2>{current.q}</h2><div className="choices">{current.o.map((o,i)=><button disabled={answer!==null} onClick={()=>setAnswer(i)} className={`choice ${answer===i?(i===current.a?"correct":"wrong"):answer!==null&&i===current.a?"correct":""}`} key={o}><span>{"ABC"[i]}</span>{o}</button>)}</div>{answer!==null&&<div className="feedback good"><b>{answer===current.a?"Excellent clinical thinking!":"Good attempt — anatomy takes practice."}</b><p>{current.e}</p><button className="primary" onClick={()=>{setAnswer(null);setStep(step+1)}}>{step===qs.length-1?"View result":"Next clue"} →</button></div>}</article> : <div className="complete"><span>✦</span><p className="eyebrow">MISSION COMPLETE</p><h2>Case solved</h2><p>You applied quadrant and regional terminology with confidence.</p><div><b>Accuracy<br /><strong>100%</strong></b><b>Reward<br /><strong>+60 XP</strong></b></div></div>}</div> }
function Explorer(){ const [area,setArea]=useState("RLQ"); const info:Record<string,[string,string]>={RLQ:["Right Lower Quadrant","Appendix, cecum, and portions of the small intestine are commonly associated here."],RUQ:["Right Upper Quadrant","The liver and gallbladder are commonly associated here."],LUQ:["Left Upper Quadrant","The stomach and spleen are commonly associated here."],LLQ:["Left Lower Quadrant","The sigmoid colon is commonly associated here."]}; return <div className="explorer"><p className="eyebrow">TAP TO EXPLORE</p><h2>Abdominal quadrants</h2><div className="explorer-grid"><div className="quadrant-map">{Object.keys(info).map(k=><button className={area===k?"selected":""} onClick={()=>setArea(k)} key={k}>{k}</button>)}</div><div className="info-card"><span>◎</span><p className="eyebrow">{area}</p><h3>{info[area][0]}</h3><p>{info[area][1]}</p><div className="quick">QUICK CHECK: Which quadrant is associated with the appendix?<b>Right Lower Quadrant</b></div></div></div><p className="caption">This explorer uses standard anatomical associations. Individual anatomy can vary.</p></div> }
function Review({player,onQuestion}:{player:Player;onQuestion:(q:Question)=>void}) { const weak=Object.entries(player.weak).sort((a,b)=>b[1]-a[1]); const picks=weak.length?allQuestions.filter(q=>q.topic===weak[0][0]).slice(0,3):instructorQuestions.slice(0,3); return <div className="review"><div className="review-hero"><span>↻</span><div><p className="eyebrow">ADAPTIVE PRACTICE</p><h2>{weak.length ? weak[0][0] : "Ready for a warm-up?"}</h2><p>{weak.length ? "This topic deserves another pass. You’ve got this." : "Answer a few instructor-aligned questions to discover your first review path."}</p></div></div>{picks.map(q=><button className="review-question" key={q.id} onClick={()=>onQuestion(q)}><span>⚡ +{q.xp}</span><b>{q.question}</b><small>{q.week ? `Instructor material · Week ${q.week}` : q.module} →</small></button>)}</div> }
function Progress({player,mastery}:{player:Player;mastery:number}) { return <div className="progress-page"><div className="mastery-card"><div className="ring"><span>{mastery}%</span></div><div><p className="eyebrow">OVERALL MASTERY</p><h2>You’re building real momentum.</h2><p>{player.correct.length} correct answers and {player.xp} XP earned.</p></div></div><div className="section-title"><div><p className="eyebrow">BADGE SHELF</p><h2>Achievements</h2></div></div><div className="badges">{[...player.badges,"Body Plane Explorer","Cavity Commander","Quadrant Detective"].map((b,i)=><div className={i<player.badges.length?"badge unlocked":"badge"} key={b}><span>{i<player.badges.length?"✦":"◇"}</span><b>{b}</b><small>{i<player.badges.length?"Unlocked":"Keep questing"}</small></div>)}</div><div className="progress-modules"><p className="eyebrow">CURRICULUM PROGRESS</p>{modules.map((m,i)=><div key={m.id}><b>{m.title}</b><span><i style={{width:i===0?"42%":"0%"}}/></span><small>{i===0?"42%":"0%"}</small></div>)}</div><div className="source-note"><b>Course content status</b><p>Generic content powers the foundation. Week 1–3 questions from your supplied BIOS 251 lectures live in <code>data/courseContent/instructor.ts</code> and are clearly labeled as instructor material.</p></div></div> }
